/* global describe */

describe('Clownface', () => {
  require('./any')
  require('./constructor')
  require('./factory')
  require('./term')
  require('./terms')
  require('./value')
  require('./values')
  require('./dataset')
  require('./datasets')
  require('./isList')
  require('./list')
  require('./node')
  require('./blankNode')
  require('./literal')
  require('./namedNode')
  require('./filter')
  require('./toArray')
  require('./forEach')
  require('./map')
  require('./toString')
  require('./in')
  require('./out')
  require('./has')
  require('./addIn')
  require('./addOut')
  require('./addList')
  require('./deleteIn')
  require('./deleteOut')
  require('./deleteList')
})
